version: "3.8"


x-pixelfed: &pixelfed
  image: ghcr.io/emilweth/pixelfed:dev
  user: ${UID:-1000}:${GID:-1000}
  networks:
    - default
  volumes:
    - 'pixelfed-public:/srv/app/public'
    - 'php-socket:/var/run/php'
    - './.docker-compose/pixelfed/php-fpm.d:/usr/local/etc/php-fpm.d:ro'
  environment:
    APP_NAME: ${APP_NAME:-Pixelfed}
    APP_URL: ${APP_URL:-https://localhost}
    APP_DOMAIN: ${APP_DOMAIN:-localhost}
    ADMIN_DOMAIN: ${ADMIN_DOMAIN:-localhost}
    SESSION_DOMAIN: ${SESSION_DOMAIN:-localhost}
    APP_KEY: ${APP_KEY:-}
    DB_CONNECTION: 'pgsql'
    DB_HOST: 'database'
    DB_PORT: '5432'
    DB_DATABASE: ${POSTGRES_DB:-pixelfed}
    DB_USERNAME: ${POSTGRES_USER:-pixelfed}
    DB_PASSWORD: ${POSTGRES_PASSWORD:-pixelfed}
    REDIS_HOST: 'redis'
    REDIS_PORT: '6379'
    SESSION_DRIVER: "redis"
    IMAGE_DRIVER: "imagick"
    CACHE_DRIVER: "redis"
    ACTIVITY_PUB: "true"
    AP_REMOTE_FOLLOW: "true"
    LOG_CHANNEL: "stderr"
    LOG_STDERR_FORMATTER: "Monolog\\Formatter\\JsonFormatter"
    STORIES_ENABLED: "true"

services:
  caddy:
    image: caddy:2-alpine
    networks:
      - default
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    volumes:
      - 'pixelfed-public:/srv/app/public'
      - 'php-socket:/var/run/php'
      - "./.docker-compose/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  copy-public:
    <<: *pixelfed
    entrypoint: ["sh", "-c"]
    command:
      - "cp -Rdf /srv/app/public /target"
    volumes:
      - pixelfed-public:/target/public

  pixelfed:
    <<: *pixelfed

  pixelfed-horizon:
    <<: *pixelfed
    entrypoint: ["sh", "-c"]
    command:
      - "php artisan horizon"

  pixelfed-migrations:
    <<: *pixelfed
    # In a different profile to avoid starting it involuntarly
    profiles: ['migration']
    entrypoint: ["sh", "-c"]
    command:
      - "php artisan migrate --force"


  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    networks:
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pixelfed}
      POSTGRES_USER: ${POSTGRES_USER:-pixelfed}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pixelfed}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw


  redis:
    image: redis:7.2-alpine
    networks:
      - default

networks:
  default:

volumes:
  php-socket:
  pixelfed-public:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data/pixelfed/public
      o: bind,uid=${UID:-1000},gid=uid=${GID:-1000}
